FROM python:3.8
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install \
    gcc nano \
    ffmpeg libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 \
    postgresql postgresql-contrib -y
RUN pip install numpy scipy matplotlib pydub pyaudio psycopg2

WORKDIR /code
COPY requirements.txt ./requirements.txt    
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /code
COPY dejavu ./dejavu
COPY app ./app


CMD [ "python","/code/app/dejavu_web.py" ]